# This action runs playwright tests nightly and on push to main to give the latest status of the main branch

name: Latest Playwright test

# Controls when the workflow will run
on:
  # Triggers the workflow nightly and on push to the main branch
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule: 
    # nightly
    - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow builds and runs the playwright tests
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Build production build
      run: npm run build
    - name: Run your tests
      run: npm run playwright_test
    - name: Upload HTML report as Artifact
      uses: actions/upload-artifact@v2
      if: always()
      with: 
        name: run-report
        path: pw-report/